MONGODB_HOST: mongodb-{{ env }}.daws90s.uk
REDIS_HOST: redis-{{ env }}.daws90s.uk
MYSQL_HOST: mysql-{{ env }}.daws90s.uk
RABBITMQ_HOST: rabbitmq-{{ env }}.daws90s.uk 
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.daws90s.uk
USER_HOST: user.backend-alb-{{ env }}.daws90s.uk
CART_HOST: cart.backend-alb-{{ env }}.daws90s.uk
SHIPPING_HOST: shipping.backend-alb-{{ env }}.daws90s.uk
PAYMENT_HOST: payment.backend-alb-{{ env }}.daws90s.uk
